### ISSUE TITLE
sub-tasks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patel22p/mytinytodo#28]
```
MyTinyTodo is a very nice and simple tool. 

I would really like to be able to add sub-tasks to a task. For example
'cleaning my apartment' can be subdivided in 'vacuum cleaning' and 'laundry'.

```

Original issue reported on code.google.com by `hannes.c.smit@gmail.com` on 23 Feb 2010 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
Any votes?
```

Original comment by `hannes.c.smit@gmail.com` on 14 Mar 2010 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
Or just a comment system to notes.
```

Original comment by `fernandom_arq@yahoo.com.br` on 19 Apr 2010 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
What do you mean Ferna..? I think you mean something else...
```

Original comment by `hannes.c.smit@gmail.com` on 19 Apr 2010 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
Yes, Subtask in hierarquical order.

TASK
  SUBTASK 1
  SUBTASK 2
    SUBTASK 2 SUBTASK

something like google tasks.
But it could be achieved adding more notes to a task, today we have just one 
note per
task.

```

Original comment by `fernandom_arq@yahoo.com.br` on 20 Apr 2010 at 4:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `maxpozd...@gmail.com` on 18 Aug 2010 at 7:11
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I just downloaded myTinyToDo and fall in love with it.
Regarding this SubTask : it would be really nice if we can see all 'due' and 
'overdue' tasks from all SubTasks in a single view.
```

Original comment by `beasce...@gmail.com` on 29 Aug 2010 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
If you are going to have Sub tasks, then it would be useful to have a template.
Add a Task from the template and all the sub tasks are added as well.
```

Original comment by `meanpeng...@gmail.com` on 30 Apr 2011 at 1:29

**Comment by GoogleCodeExporter** [comment]
```
I added another enhancement without seeing this one. I vote for this.

Some comments:
 It would be great to add sub-tasks to the task, where each sub-task can be managed the way the tasks are being managed now, i.e
 - date started
 - date ended
 - status (not-done/in-progress/done)

also, the overall progress of a task can be updated as the sub-tasks are 
completed.
```

Original comment by `ravi.nal...@gmail.com` on 16 May 2011 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
Yes the Sub-Task Feature would be absolute great and a real killer Feature i 
search for for over the web for months...
```

Original comment by `72quad...@gmail.com` on 29 Feb 2012 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
I agree it would be very usefull. Now I write subtasks inside note field (not 
so useful). So waiting subtasks so much!
```

Original comment by `gizzat` on 1 Mar 2012 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
I'm thinking about to add one level of subtasks, root level will be called 
"Task group". Why to have many sublevels, is it realy used?
```

Original comment by `maxpozd...@gmail.com` on 20 Mar 2012 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
Yes Sub-Tasks are often really useful for example in the progress of doing 
things, you really often recognize that one single task get's a huge thing 
(like the simple task debug f.e.) and is better handled with little subtasks... 
So the only thing that's realla great at  the Max app "the hit list" is the 
good way it deals with these...

Thank you
```

Original comment by `72quad...@gmail.com` on 20 Mar 2012 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
I meant subtasks in many levels:
Root task
--Subtask level 1
-- -- Subtask level 2
--..... --Subtask level N

How many levels of subtasks is need? As for me - only one.
```

Original comment by `maxpozd...@gmail.com` on 20 Mar 2012 at 8:01

**Comment by GoogleCodeExporter** [comment]
```
Yes that's it. Infinite is the best, but 5 is something like infinite perhaps...
```

Original comment by `72quad...@gmail.com` on 20 Mar 2012 at 8:22

**Comment by GoogleCodeExporter** [comment]
```
Maxim, I agree with you - 1 level of subtask is most commonly used and is
easier to realize.
Of course potentially it is good to have more than 1 level of subtask, but
1 is OK I think.
As for me - I always use task notes as subtasks. I write there:
[ + ] This thing is done
[ - ] This thing to do
[ - ] Another thing to do

So even 1 level is much better than just notes :)

Thank you.
```

Original comment by `gizzat` on 21 Mar 2012 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Infinite seems best. Is that hard to make?
Op 21 mrt. 2012 11:00 schreef <mytinytodo@googlecode.com> het volgende:
```

Original comment by `hannes.c.smit@gmail.com` on 22 Mar 2012 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Hello there,
because I was trying to import my google tasks to your great project, I'm a bit 
annoying by that lake. It would be great to have 'infinite' sub-level. Because 
I use todolists to manage my dev, I mainly organize my stuff like that :
Main project
-sub project
--functionality/bug
---things to be done

I know there are tags, but it looks much messy without sub list, and I see more 
tags as complement like tagging "plugin" "theme" the sub projects

```

Original comment by `pessina....@gmail.com` on 28 Mar 2012 at 1:33

**Comment by GoogleCodeExporter** [comment]
```
i've added this to the issue list at: https://github.com/alex-LE/myTinyTodo
if you want, we may discuss it there
```

Original comment by `eagled...@gmail.com` on 6 Apr 2012 at 11:04

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
starpeng, @shlomitsur, @agastyo-rg, @boyuan-li, @jwp8cf, @nnolucero, @vmateianu, @daniel-cordeiro, @jamiddd, @lazerlabs, @pinougiio, @jyeung205, @LeeHyung-corp, @pranshu-aggarwal, @JustinG1552, @webDrag0n, @lapreamarcelo, @yadinae, @techonomics69, @NEEPUslc, @katiejlee, @dmyger, @mafa1993, @jones-so, @nwillemse, @W-Lawless, @nilayparikh, @hrtksalunke, @oliver021, @Cheryl008, @sneakywarwolf, @mehrdade, @samisbakedham, @drunaar, @pmichalik77m, @Aurelie-Dubost, @monknommy, @FriendlyUser, @oscarm417, @jiawanchen, @sandoche, @cachenow, @ghost0x, @DarkSywall, @JiangJiaqi90, @romkij, @p3psi-boo, @hadrianl, @19920716, @erson

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Neilsons, @alaskacanyon, @cutie, @DanielsCode, @sm18lr88, @sachacs, @johnnyjoppa99, @fritomontana, @ubermachine, @AbhiDeactive, @projenix, @1adetbeyfendi, @wikipetal, @thePoddar, @iamfrankie, @kxxg1, @jrogs, @bfday, @sdrawkab, @DragonBtc93, @SadNTasteless, @Hocza-Jozsef-Szabolcs, @sickerin, @kaspaycc, @nukezie, @dmanoloff, @alexnava86, @Ctrotter456, @luatnd, @jiajingk, @eankhbayar, @TC94615, @guccimerkel, @s0kil, @laplacian-k, @dianalow, @michaelcjl, @Ba-I-T-o, @tin-phan, @wangweiqi20020221, @Gorbov, @muzizl, @nh43de, @mry77, @, @disgone, @Rowb0tt, @lawtatfaitony, @lospiros, @Balder1840

**Comment by jones-so** [comment]
您的邮件创视已经收到，请等待我给您的回复，祝您开心！
